#!/bin/bash

type truecrypt >/dev/null 2>&1 || 
{
	echo "Missing Dependencies...\n"
	while true; do
	    read -p "Do you wish to install dependencies?" yn
	    case $yn in
		[Yy]* ) 
			echo >&2 "Missing Dependency: Truecrypt\n"; 
			sudo wget https://www.grc.com/misc/truecrypt/truecrypt-7.1a-linux-console-x64.tar.gz;
			gunzip truecrypt-7.1a-linux-console-x64.tar.gz;
			tar -xvf truecrypt-7.1a-linux-console-x64.tar;
			rm truecrypt-7.1a-linux-console-x64.*;
			truecrypt-7.1a-setup-console-x64;
			rm truecrypt-7.1a-setup-console-x64;
			type truecrypt >/dev/null 2>&1 ||
			{
				echo "Failed to detect dependencies... exiting...";
				exit 1;	
			}
			break;;
		[Nn]* ) exit;;
		* ) echo "Please answer yes or no.";;
	    esac
	done

}
while true; do
    read -p "Do you wish to create a new file system image (uses minimum settings)?" yn
    case $yn in
	[Yy]* ) 
		truecrypt -c --volume-type=Normal --size=300000 --encryption=AES --filesystem=FAT --hash=SHA-512;
		break;;
	[Nn]* ) 

		break;;
	* ) echo "Please answer yes or no.";;
    esac
done
echo "============================================================================" 
echo "Truecrypt Commands:"
echo "Create custom image   Usage: 'truecrypt -c'"
echo "Mount image           Usage: 'truecrypt --mount <volume> <mountpoint>"
echo "============================================================================" 
make stegomax;
stegomax;